# Generated by Django 4.1.4 on 2022-12-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=1024, null=True)),
                ('jobUrl', models.CharField(max_length=1024, null=True)),
                ('companyName', models.CharField(max_length=256, null=True)),
                ('companyImage', models.ImageField(null=True, upload_to='company/logo-social.png')),
                ('salary', models.IntegerField(null=True)),
                ('isRemote', models.BooleanField(null=True)),
                ('jobType', models.CharField(max_length=32, null=True)),
                ('experience', models.CharField(max_length=32, null=True)),
                ('website', models.CharField(blank=True, max_length=64, null=True)),
                ('websiteIcon', models.ImageField(blank=True, null=True, upload_to='company/logo-social.png')),
            ],
        ),
    ]
