# Generated by Django 4.1.4 on 2022-12-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='companyImage',
            field=models.ImageField(blank=True, null=True, upload_to='company/logo-social.png'),
        ),
        migrations.AlterField(
            model_name='job',
            name='companyName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='isRemote',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobTitle',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobType',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobUrl',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
