# Generated by Django 4.1.4 on 2022-12-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_job_companyimage_alter_job_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='creationTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
